# Generated by Django 6.0.4 on 2026-04-26 10:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('birth_date', models.DateField(verbose_name='Birth Date')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=10, verbose_name='Gender')),
                ('current_school_level', models.CharField(choices=[('1', '1 Class'), ('2', '2 Class'), ('3', '3 Class'), ('4', '4 Class'), ('5', '5 Class'), ('6', '6 Class'), ('7', '7 Class'), ('8', '8 Class'), ('9', '9 Class'), ('10', '10 Class'), ('11', '11 Class'), ('12', '12 Class')], max_length=20, verbose_name='Current School')),
                ('enrollment_status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('graduated', 'Graduated'), ('transferred', 'Transferred')], max_length=30, verbose_name='Enrollment Status')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos', verbose_name='Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
    ]
